### ISSUE TITLE
很棒的项目，可是为什么star和fork这么少？

### ISSUE THREAD

**Issue by znx970902** [NJUPTFreeExams/NJUPT-General-Free-Exams#1]
另外请问可以发布一些计算机专业课的考试资料吗，比如数据结构什么。非常感谢

**Comment by Wonz5130** [comment]
> 另外请问可以发布一些计算机专业课的考试资料吗，比如数据结构什么。非常感谢

希望大家多多支持，给个 `star` 和 `fork` ，把此项目宣传出去（五月底会正式宣传）。
计算机专业课的考试资料可以到这个项目仓库找：https://github.com/NJUPTFreeExams/NJUPT_CS_Free_Exams

**Comment by znx970902** [comment]
> > 另外请问可以发布一些计算机专业课的考试资料吗，比如数据结构什么。非常感谢
> 
> 希望大家多多支持，给个 `star` 和 `fork` ，把此项目宣传出去（五月底会正式宣传）。
> 计算机专业课的考试资料可以到这个项目仓库找：https://github.com/NJUPTFreeExams/NJUPT_CS_Free_Exams
收到，感谢贡献

**Comment by bmxbmx3** [comment]
I’m afraid if school knows about this repo,would it be banned like [REKCARC-TSC-UHT repo](https://github.com/Trinkle23897/THU-CST-Cracker)?

**Comment by imguozr** [comment]
Thank you very much for your reminder. At this time, we do not have a formal license and it seems that the THU-CST-Cracker was banned due to uploading of textbooks and violence of its own license. We will consider to add a CC 4.0 or some other license in the next few days. By the way, I think the college has no reason to ban us if we did nothing wrong :)

**Comment by imguozr** [comment]
> I’m afraid if school knows about this repo,would it be banned like [REKCARC-TSC-UHT repo](https://github.com/Trinkle23897/THU-CST-Cracker)?

Thank you very much for your reminder. At this time, we do not have a formal license and it seems that the THU-CST-Cracker was banned due to uploading of textbooks and violence of its own license. We will consider to add a CC 4.0 or some other license in the next few days. By the way, I think the college has no reason to ban us if we did nothing wrong :)
